name: Test and report coverage

on: [push]

jobs:
  testreport:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # -e/editable is important for coverage to work
      - name: Create doc tests
        run: |
          mkdir tests/autogen_phmdoctest
          phmdoctest README.md --outfile tests/autogen_phmdoctest/test_readme.py
      - name: Test with pytest and coverage.py
        run: coverage run --branch -m pytest
      - name: Report coverage
        run: coverage report